// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ebillets_jo2024_API.Data;

#nullable disable

namespace ebillets_jo2024_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251022095350_SyncModelsWithDatabase")]
    partial class SyncModelsWithDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ebillets_jo2024_API.Models.Administrateur", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAdmin");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAdmin"));

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dateAjout");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    b.Property<string>("RoleDetail")
                        .HasColumnType("longtext")
                        .HasColumnName("roleDetail");

                    b.HasKey("IdAdmin");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("administrateur");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Billet", b =>
                {
                    b.Property<int>("IdBillet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idBillet");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBillet"));

                    b.Property<string>("CleBillet")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("cleBillet");

                    b.Property<string>("CleFinale")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("cleFinale");

                    b.Property<string>("CleSecrete")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dateEmission");

                    b.Property<int>("IdOffre")
                        .HasColumnType("int")
                        .HasColumnName("idOffre");

                    b.Property<int>("IdReservation")
                        .HasColumnType("int")
                        .HasColumnName("idReservation");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("qrcode");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("statut");

                    b.Property<string>("TitulaireNom")
                        .HasColumnType("longtext")
                        .HasColumnName("titulaireNom");

                    b.HasKey("IdBillet");

                    b.HasIndex("IdOffre");

                    b.HasIndex("IdReservation");

                    b.ToTable("billet");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Offre", b =>
                {
                    b.Property<int>("IdOffre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOffre"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("NbPersonnes")
                        .HasColumnType("int");

                    b.Property<string>("NomOffre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdOffre");

                    b.ToTable("offre");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPaiement"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext");

                    b.HasKey("IdPaiement");

                    b.HasIndex("IdReservation")
                        .IsUnique();

                    b.ToTable("paiement");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Panier", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPanier");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPanier"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dateCreation");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    b.HasKey("IdPanier");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("panier");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.PanierOffre", b =>
                {
                    b.Property<int>("IdPanier")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdOffre")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Quantite")
                        .HasColumnType("int")
                        .HasColumnName("quantite");

                    b.HasKey("IdPanier", "IdOffre");

                    b.HasIndex("IdOffre");

                    b.ToTable("panier_offre");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idReservation");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReservation"));

                    b.Property<string>("CleFinale")
                        .HasColumnType("longtext")
                        .HasColumnName("cleFinale");

                    b.Property<string>("CleReservation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("cleReservation");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dateReservation");

                    b.Property<int>("IdOffre")
                        .HasColumnType("int")
                        .HasColumnName("idOffre");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    b.Property<string>("QrCode")
                        .HasColumnType("longtext")
                        .HasColumnName("qrcode");

                    b.Property<int>("Quantite")
                        .HasColumnType("int")
                        .HasColumnName("quantite");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("statut");

                    b.HasKey("IdReservation");

                    b.HasIndex("IdOffre");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.ScanBillet", b =>
                {
                    b.Property<int>("IdScan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idScan");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdScan"));

                    b.Property<DateTime>("DateScan")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dateScan");

                    b.Property<int>("IdBillet")
                        .HasColumnType("int")
                        .HasColumnName("idBillet");

                    b.Property<int>("IdEmploye")
                        .HasColumnType("int")
                        .HasColumnName("idEmploye");

                    b.Property<string>("Resultat")
                        .HasColumnType("longtext")
                        .HasColumnName("resultat");

                    b.HasKey("IdScan");

                    b.HasIndex("IdBillet");

                    b.HasIndex("IdEmploye");

                    b.ToTable("scan_billet");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("CleUtilisateur")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("cleUtilisateur");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dateCreation");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("motDePasseHash");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("utilisateur");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Administrateur", b =>
                {
                    b.HasOne("ebillets_jo2024_API.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Billet", b =>
                {
                    b.HasOne("ebillets_jo2024_API.Models.Offre", "Offre")
                        .WithMany()
                        .HasForeignKey("IdOffre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ebillets_jo2024_API.Models.Reservation", "Reservation")
                        .WithMany("Billets")
                        .HasForeignKey("IdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offre");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Paiement", b =>
                {
                    b.HasOne("ebillets_jo2024_API.Models.Reservation", "Reservation")
                        .WithOne("Paiement")
                        .HasForeignKey("ebillets_jo2024_API.Models.Paiement", "IdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Panier", b =>
                {
                    b.HasOne("ebillets_jo2024_API.Models.Utilisateur", "Utilisateur")
                        .WithMany("Paniers")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.PanierOffre", b =>
                {
                    b.HasOne("ebillets_jo2024_API.Models.Offre", "Offre")
                        .WithMany("PaniersOffres")
                        .HasForeignKey("IdOffre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ebillets_jo2024_API.Models.Panier", "Panier")
                        .WithMany("PaniersOffres")
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offre");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Reservation", b =>
                {
                    b.HasOne("ebillets_jo2024_API.Models.Offre", "Offre")
                        .WithMany("Reservations")
                        .HasForeignKey("IdOffre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ebillets_jo2024_API.Models.Utilisateur", "Utilisateur")
                        .WithMany("Reservations")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offre");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.ScanBillet", b =>
                {
                    b.HasOne("ebillets_jo2024_API.Models.Billet", "Billet")
                        .WithMany("ScansBillets")
                        .HasForeignKey("IdBillet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ebillets_jo2024_API.Models.Utilisateur", "Employe")
                        .WithMany()
                        .HasForeignKey("IdEmploye")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Billet");

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Billet", b =>
                {
                    b.Navigation("ScansBillets");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Offre", b =>
                {
                    b.Navigation("PaniersOffres");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Panier", b =>
                {
                    b.Navigation("PaniersOffres");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Reservation", b =>
                {
                    b.Navigation("Billets");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("ebillets_jo2024_API.Models.Utilisateur", b =>
                {
                    b.Navigation("Paniers");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
