// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ebillets_jo2024_API.Data;

#nullable disable

namespace ebillets_jo2024.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ebillets_jo2024.Models.Offre", b =>
                {
                    b.Property<int>("IdOffre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOffre"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("NbPersonnes")
                        .HasColumnType("int");

                    b.Property<string>("NomOffre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdOffre");

                    b.ToTable("offre");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPaiement"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext");

                    b.HasKey("IdPaiement");

                    b.HasIndex("IdReservation")
                        .IsUnique();

                    b.ToTable("paiement");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Panier", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPanier"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdPanier");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("panier");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.PanierOffre", b =>
                {
                    b.Property<int>("IdPanier")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdOffre")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("IdPanier", "IdOffre");

                    b.HasIndex("IdOffre");

                    b.ToTable("panier_offre");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReservation"));

                    b.Property<string>("CleFinale")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CleReservation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdOffre")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("QrCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext");

                    b.HasKey("IdReservation");

                    b.HasIndex("IdOffre");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.ScanBillet", b =>
                {
                    b.Property<int>("IdScan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdScan"));

                    b.Property<DateTime>("DateScan")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmploye")
                        .HasColumnType("int");

                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<string>("Resultat")
                        .HasColumnType("longtext");

                    b.HasKey("IdScan");

                    b.HasIndex("IdEmploye");

                    b.HasIndex("IdReservation");

                    b.ToTable("scan_billet");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("CleUtilisateur")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("utilisateur");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Paiement", b =>
                {
                    b.HasOne("ebillets_jo2024.Models.Reservation", "Reservation")
                        .WithOne("Paiement")
                        .HasForeignKey("ebillets_jo2024.Models.Paiement", "IdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Panier", b =>
                {
                    b.HasOne("ebillets_jo2024.Models.Utilisateur", "Utilisateur")
                        .WithMany("Paniers")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.PanierOffre", b =>
                {
                    b.HasOne("ebillets_jo2024.Models.Offre", "Offre")
                        .WithMany("PaniersOffres")
                        .HasForeignKey("IdOffre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ebillets_jo2024.Models.Panier", "Panier")
                        .WithMany("PaniersOffres")
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offre");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Reservation", b =>
                {
                    b.HasOne("ebillets_jo2024.Models.Offre", "Offre")
                        .WithMany("Reservations")
                        .HasForeignKey("IdOffre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ebillets_jo2024.Models.Utilisateur", "Utilisateur")
                        .WithMany("Reservations")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offre");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.ScanBillet", b =>
                {
                    b.HasOne("ebillets_jo2024.Models.Utilisateur", "Employe")
                        .WithMany()
                        .HasForeignKey("IdEmploye")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ebillets_jo2024.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("IdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Offre", b =>
                {
                    b.Navigation("PaniersOffres");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Panier", b =>
                {
                    b.Navigation("PaniersOffres");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Reservation", b =>
                {
                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("ebillets_jo2024.Models.Utilisateur", b =>
                {
                    b.Navigation("Paniers");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
